taskmanager/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('password_change/', PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done'), template_name='accounts/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy("accounts:password_reset_done"), 
                                                      email_template_name='accounts/custom_password_reset_email.html',
                                                      template_name="accounts/password_reset_form.html",
                                                      ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm_form.html",
                                                                     success_url=reverse_lazy("accounts:password_reset_complete"),
                                                                     ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name='password_reset_complete'),
]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('tasks.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskmanager/tasks/urls.py
from django.urls import path, register_converter
from django.views.generic import TemplateView
from .views import TaskListView, TaskCreateView, TaskDetailView, TaskUpdateView, TaskDeleteView
from . import views, converters

register_converter(converters.DateConverter, 'ddmmyyyy')

app_name = 'tasks'

urlpatterns = [
    path('', views.task_home, name='home'),
    path('help/', TemplateView.as_view(template_name='tasks/help.html'), name='help'),
    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/new/', TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/<int:pk>/edit/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('tasks/<ddmmyyyy:date>/', TaskListView.as_view(), name='task-by-date'),
    path('tasks/sprint/add_task/<int:pk>/', views.create_task_on_sprint, name='task-add-to-sprint'),
    path('tasks/home/', views.task_home, name='task-home'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('contact-success/', TemplateView.as_view(template_name='tasks/contact_success.html'), name='contact-success'),
]

taskmanager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    STATUS_CHOICES = [
        ("UNASSIGNED", "Unassigned"),
        ("IN_PROGRESS", "In Progress"),
        ("DONE", "Done"),
        ("ARCHIVED", "Archived"),
    ]
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=False, default="")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="UNASSIGNED",
                              db_comment="Can be UNASSIGNED, IN_PROGRESS, DONE, or ARCHIVED.")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    file_upload = models.FileField(upload_to='tasks/files/', null=True, blank=True)
    image_upload = models.ImageField(upload_to='tasks/images/', null=True, blank=True)
    creator = models.ForeignKey(
        User, related_name="created_tasks", on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name="owned_tasks", on_delete=models.CASCADE,
                              null=False, db_comment="Foreign Key to the User who currently owns the task.")
    epic = models.ForeignKey(
        'Epic', on_delete=models.SET_NULL, null=True, related_name="tasks")

    class Meta:
        db_table_comment = "Holds information about tasks.",
        constraints = [
            models.CheckConstraint(check=models.Q(status='UNASSIGNED') | models.Q(status='IN_PROGRESS') | models.Q(status='DONE') | models.Q(status='ARCHIVED'), name='status_check')
        ]


class Sprint(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True, default="")
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_sprints", on_delete=models.CASCADE)
    tasks = models.ManyToManyField('Task', related_name="sprints", blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(check=models.Q(start_date__lt=models.F(
                'end_date')), name='start_date_before_end_date')
        ]


class Epic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        User, related_name="created_epics", on_delete=models.CASCADE)

taskmanager/tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'owner', 'file_upload', 'image_upload']
        
class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

taskmanager/tasks/views.py
from django.shortcuts import render
from .models import Task
from .forms import TaskForm, ContactForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from . import services
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import redirect
from datetime import date
from collections import defaultdict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
# Create your views here.

def task_home(request):
    tasks = Task.objects.filter(status__in=["UNASSIGNED", "IN_PROGRESS", "DONE", "ARCHIVED"])
    
    context = defaultdict(list)
    for task in tasks:
        if task.status == "UNASSIGNED":
            context['unassigned_tasks'].append(task)
        elif task.status == "IN_PROGRESS":
            context['in_progress_tasks'].append(task)
        elif task.status == "DONE":
            context['done_tasks'].append(task)
        elif task.status == "ARCHIVED":
            context['archived_tasks'].append(task)
            
    return render(request, 'tasks/home.html', context)

def task_by_date(request: HttpRequest, by_date: date) -> HttpResponse:
    tasks = services.get_tasks_by_date(by_date)
    context = {'tasks': tasks}
    return render(request, 'task_list.html', context)

@permission_required("tasks.add_task")
def create_task_on_sprint(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    if request.method == 'POST':
        task_data: dict[str, str] = {
            'title': request.POST['title'],
            'description': request.POST.get('description', ''),
            'status': request.POST.get('status', 'UNASSIGNED'),
        }
        task = services.create_task_and_add_to_sprint(task_data, pk, request.user)
        return redirect('task-detail', task_id=task.id)
    raise Http404("Not found")

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'task_list.html'
    context_object_name = 'tasks'

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'
    
class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskForm
    
    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', kwargs={'pk': self.object.id})

class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskForm
    
    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', kwargs={'pk': self.object.id})
    
class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks/task_confirm_delete.html'
    success_url = reverse_lazy('tasks:task-list')
    
class ContactFormView(FormView):
    template_name = 'tasks/contact_form.html'
    form_class = ContactForm
    success_url = reverse_lazy('tasks:contact-success')
    
    def form_valid(self, form):
        subject = form.cleaned_data.get('subject')
        message = form.cleaned_data.get('message')
        from_email = form.cleaned_data.get('from_email')
        
        services.send_contact_email(subject, message, from_email, ['admin@example.com'])
        
        return super().form_valid(form)

taskmanager/templates/tasks/_footer.html
<footer class="footer mt-auto py-3 bg-light text-center">
    <div class="container">
        <a href="{% url 'tasks:help' %}" class="text-dark">Help</a>
        <a href="{% url 'tasks:contact' %}" class="text-dark">Contact</a>
    </div>
</footer>

taskmanager/templates/tasks/_header.html
{% load static %}

<header class="d-flex justify-content-between align-items-center p-3">
    <!-- Left side -->
    <div class="d-flex align-items-center">
        <!-- Logo -->
        <img src="{% static 'images/logo.png' %}" alt="Task Manager" width="50" class="mr-3">

        <a href="{% url 'tasks:task-home' %}" class="btn btn-secondary mr-2" role="button">Home</a>
        <a href="{% url 'tasks:task-create' %}" class="btn btn-primary" role="button">Create</a>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'accounts:logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger ml-2">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-success ml-2" role="button">Login</a>
        {% endif %}
    </div>

    <!-- Right side -->
    <div class="d-flex">
        <input type="text" class="form-control" id="search" placeholder="Search">
        <button type="button" class="btn btn-success ml-2">Search</button>
    </div>
</header>

taskmanager/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ page_title|default:"Default Title" }}{% endblock %}</title>
    <!-- CSS files -->
    {% block extra_css %}{% endblock %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">    <!-- <link rel="stylesheet" href="styles.css"> -->
</head>
<body>

    {% include "tasks/_header.html" %}
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% include "tasks/_footer.html" %}
    <!-- JS files -->
    {% block extra_javascript %}{% endblock %}
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <!-- <script src="script.js"></script> -->
</body>
</html>

taskmanager/templates/tasks/contact_form.html
{% extends "tasks/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="w-50">
        <div class="card">
            <div class="card-header">
                <h2 class="text-center">Contact Us</h2>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'tasks:contact' %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                            {{ field|add_class:"form-control" }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary w-100">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

taskmanager/templates/tasks/contact_success.html
{% extends "tasks/base.html" %}
{% block content %}
<div class="container">
    <h1>Contact Form Submitted</h1>
    <p>Thank you for contacting us. We will get back to you soon.</p>
    <a href="{% url 'tasks:home' %}" class="btn btn-primary">Back to Home</a>
</div>
{% endblock %}

taskmanager/templates/tasks/help.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                Help Page
            </div>
            <div class="card-body">
                <h5 class="card-title">What is a task manager?</h5>
                <p class="card-text">A task management system is software that helps users organize and track the progress of tasks.</p>
            </div>
        </div>
    </div>
{% endblock %}

taskmanager/templates/tasks/home.html
{% extends "tasks/base.html" %}

{% block content %}
    <div class="container mt-5">
        <h2>Tasks by Status</h2>
        <div class="row mt-4">

            <!-- Unassigned Tasks -->
            <div class="col-md-3">
                <h4>Unassigned</h4>
                {% for task in unassigned_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- In Progress Tasks -->
            <div class="col-md-3">
                <h4>In Progress</h4>
                {% for task in in_progress_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Completed Tasks -->
            <div class="col-md-3">
                <h4>Completed</h4>
                {% for task in done_tasks %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a></h5>
                            <p class="card-text">Owner: {{ task.owner.username|default:"None" }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div> <!-- End of row -->


    </div> <!-- End of container -->
{% endblock %}

taskmanager/templates/tasks/task_confirm_delete.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>Delete Task</h1>
  <p>Are you sure you want to delete the task "{{ task.name }}"?</p>
  <form method="post">
  {% csrf_token %}
  <button type="submit">Yes, delete</button>
  </form>
  <a href="{% url 'tasks:task-detail' task.id %}">No, take me back</a>
{% endblock %}

taskmanager/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>{{ task.title }}</h1>
  <h2>Description</h2>
  <p>{{ task.description }}</p>
  {% if task.file_upload %}
    <a href="{{ task.file_upload.url }}" download>Download File</a>
  {% endif %}
  {% if task.image_upload %}
    <div>
      <img src="{{ task.image_upload.url }}" alt="Task Image" style="max-width: 300px;">
    </div>
  {% endif %}
  <a href="{% url 'tasks:task-update' task.id %}">Edit</a>
  <a href="{% url 'tasks:task-delete' task.id %}">Delete</a>
  <a href="{% url 'tasks:task-list' %}">List</a>
{% endblock %}

taskmanager/templates/tasks/task_form.html
{% extends "tasks/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center align-items-center vh-100">
	<div class="w-50">
		<div class="card">
			<div class="card-header">
				<h2 class="text-center">Create a New Task</h2>
			</div>
			<div class="card-body">
				<form id="taskForm" method="post" action="{% if task.pk %}{% url 'tasks:task-update' task.pk %}{% else %}{% url 'tasks:task-create' %}{% endif %}">
					{% csrf_token %}
					{% for field in form %}
						<div class="mb-3">
							<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
							{% if field.errors %}
								<div class="alert alert-danger">
									{{ field.errors }}
								</div>
							{% endif %}
							{{ field|add_class:"form-control" }}
						</div>
					{% endfor %}

					{% if form.non_field_errors %}
						<div class="alert alert-danger">
							<ul>
								{% for error in form.non_field_errors %}
									<li>{{ error }}</li>
								{% endfor %}
							</ul>
						</div>
					{% endif %}
					<button type="submit" class="btn btn-primary w-100">Save</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block extra_javascript %}
<script>
	document.getElementById('taskForm').addEventListener('submit', function(event) {
		this.querySelector('button[type="submit"]').disabled = true;
	});
</script>
{% endblock %}

taskmanager/templates/tasks/task_list.html
{% extends "tasks/base.html" %}

{% block content %}
  <h1>Task List</h1>
  <ul>
  {% for task in tasks %}
    <li class="list-unstyled">
      <a href="{% url 'tasks:task-detail' task.id %}">{{ task.title }}</a>
    </li>
  {% empty %}
    <li>No tasks available.</li>
  {% endfor %}
  </ul>
{% endblock %}